<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\FlashSale;
use App\Models\FlashSaleProduct;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class ChocolateCatalogSeeder extends Seeder
{
    public function run(): void
    {
        // Clean out generic or non-chocolate records
        Product::where('sku', 'not like', 'CHOC-%')->forceDelete();
        Category::whereNotIn('slug', [
            'dark-chocolate', 'milk-chocolate', 'truffles-pralines', 'white-chocolate',
            'gift-boxes', 'hot-chocolate-cocoa', 'barks-dragees', 'sugar-free-vegan',
        ])->delete();
        Brand::whereNotIn('slug', [
            'lindt', 'godiva', 'valrhona', 'neuhaus', 'ghirardelli',
            'ferrero-rocher', 'venchi', 'patchi', 'leonidas', 'amedei-tuscany',
        ])->delete();

        $categoriesData = [
            [
                'name' => 'Dark Chocolate',
                'slug' => 'dark-chocolate',
                'description' => 'Single-origin bars and intensely rich dark chocolate with 70% to 99% pure cocoa.',
                'image' => 'https://images.unsplash.com/photo-1548907040-4baa42d10919?q=80&w=300&auto=format&fit=crop',
                'sort_order' => 1,
            ],
            [
                'name' => 'Milk Chocolate',
                'slug' => 'milk-chocolate',
                'description' => 'Silky Swiss and Belgian milk chocolate bars blended with alpine milk, roasted nuts, and caramel.',
                'image' => 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=300&auto=format&fit=crop',
                'sort_order' => 2,
            ],
            [
                'name' => 'Truffles & Pralines',
                'slug' => 'truffles-pralines',
                'description' => 'Melt-in-your-mouth chocolate ganache truffles, Marc de Champagne bites, and crunchy hazelnut pralines.',
                'image' => 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?q=80&w=300&auto=format&fit=crop',
                'sort_order' => 3,
            ],
            [
                'name' => 'White & Blonde Chocolate',
                'slug' => 'white-chocolate',
                'description' => 'Creamy cocoa butter confections infused with Bourbon vanilla beans, caramelized milk, and freeze-dried berries.',
                'image' => 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?q=80&w=300&auto=format&fit=crop',
                'sort_order' => 4,
            ],
            [
                'name' => 'Artisan Gift Boxes',
                'slug' => 'gift-boxes',
                'description' => 'Opulent assortment boxes and velvet hampers curated for celebrations, holidays, and luxury gifting.',
                'image' => 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?q=80&w=300&auto=format&fit=crop',
                'sort_order' => 5,
            ],
            [
                'name' => 'Hot Chocolate & Cocoa',
                'slug' => 'hot-chocolate-cocoa',
                'description' => 'Authentic drinking chocolate flakes, single-estate Dutch-processed cocoa, and spiced Mayan chocolate blends.',
                'image' => 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?q=80&w=300&auto=format&fit=crop',
                'sort_order' => 6,
            ],
            [
                'name' => 'Barks & Dragees',
                'slug' => 'barks-dragees',
                'description' => 'Crisp chocolate slabs loaded with sea-salted almonds, pistachios, candied peel, and chocolate espresso beans.',
                'image' => 'https://images.unsplash.com/photo-1570476922354-81227cdbb76c?q=80&w=300&auto=format&fit=crop',
                'sort_order' => 7,
            ],
            [
                'name' => 'Sugar-Free & Vegan',
                'slug' => 'sugar-free-vegan',
                'description' => 'Plant-based oat milk chocolate creations and keto-friendly dark bars sweetened with pure monk fruit and stevia.',
                'image' => 'https://images.unsplash.com/photo-1511381939415-e44015466834?q=80&w=300&auto=format&fit=crop',
                'sort_order' => 8,
            ],
        ];

        $categories = [];
        foreach ($categoriesData as $c) {
            $categories[$c['slug']] = Category::updateOrCreate(
                ['slug' => $c['slug']],
                [
                    'name' => $c['name'],
                    'description' => $c['description'],
                    'image' => $c['image'],
                    'sort_order' => $c['sort_order'],
                    'is_active' => true,
                ]
            );
        }

        $brandsData = [
            [
                'name' => 'Lindt & Sprüngli',
                'slug' => 'lindt',
                'description' => 'Swiss Master Chocolatier crafting iconic melt-in-the-mouth Lindor and Excellence bars since 1845.',
                'logo' => 'https://images.unsplash.com/photo-1548907040-4baa42d10919?q=80&w=200&auto=format&fit=crop',
            ],
            [
                'name' => 'Godiva Chocolatier',
                'slug' => 'godiva',
                'description' => 'Belgian heritage luxury chocolatier renowned for velvet ganache and signature gold ballotins.',
                'logo' => 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?q=80&w=200&auto=format&fit=crop',
            ],
            [
                'name' => 'Valrhona',
                'slug' => 'valrhona',
                'description' => 'French Grand Cru gastronomy chocolate crafted in Tain-l’Hermitage, celebrated by world-renowned pastry chefs.',
                'logo' => 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=200&auto=format&fit=crop',
            ],
            [
                'name' => 'Neuhaus',
                'slug' => 'neuhaus',
                'description' => 'The historic Brussels chocolatier who invented the original Belgian praline in 1912.',
                'logo' => 'https://images.unsplash.com/photo-1575372587186-50020fd3b811?q=80&w=200&auto=format&fit=crop',
            ],
            [
                'name' => 'Ghirardelli',
                'slug' => 'ghirardelli',
                'description' => 'San Francisco handcrafted chocolate maker famous for luscious caramel-filled squares since 1852.',
                'logo' => 'https://images.unsplash.com/photo-1516738901171-8eb4fc13bd20?q=80&w=200&auto=format&fit=crop',
            ],
            [
                'name' => 'Ferrero Rocher',
                'slug' => 'ferrero-rocher',
                'description' => 'Golden spheres of roasted whole hazelnut, rich cocoa cream, and crispy wafer shell.',
                'logo' => 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?q=80&w=200&auto=format&fit=crop',
            ],
            [
                'name' => 'Venchi',
                'slug' => 'venchi',
                'description' => 'Piedmontese artisan chocolate maker crafting heritage Gianduja and Chocoviar since 1878.',
                'logo' => 'https://images.unsplash.com/photo-1526081347589-7fa3cb41b4b2?q=80&w=200&auto=format&fit=crop',
            ],
            [
                'name' => 'Patchi',
                'slug' => 'patchi',
                'description' => 'The pinnacle of luxury chocolate gift giving and haute chocolaterie.',
                'logo' => 'https://images.unsplash.com/photo-1549007953-2f2dc0b24019?q=80&w=200&auto=format&fit=crop',
            ],
            [
                'name' => 'Leonidas',
                'slug' => 'leonidas',
                'description' => 'Belgian master confectioners using 100% pure cocoa butter and traditional recipes.',
                'logo' => 'https://images.unsplash.com/photo-1511381939415-e44015466834?q=80&w=200&auto=format&fit=crop',
            ],
            [
                'name' => 'Amedei Tuscany',
                'slug' => 'amedei-tuscany',
                'description' => 'Multi-award-winning Italian bean-to-bar artisan creating Porcelana and Blanco de Criollo.',
                'logo' => 'https://images.unsplash.com/photo-1587132137056-bfbf0166836e?q=80&w=200&auto=format&fit=crop',
            ],
        ];

        $brands = [];
        foreach ($brandsData as $b) {
            $brands[$b['slug']] = Brand::updateOrCreate(
                ['slug' => $b['slug']],
                [
                    'name' => $b['name'],
                    'description' => $b['description'],
                    'logo' => $b['logo'],
                    'is_active' => true,
                ]
            );
        }

        $productsData = [
            [
                'name' => 'Valrhona Guanaja 70% Dark Chocolate Grand Cru Bar',
                'slug' => 'valrhona-guanaja-70-dark-chocolate-bar',
                'short_description' => 'Iconic French grand cru dark chocolate with warm floral notes and a lingering roasted finish.',
                'description' => 'Crafted in Tain-l’Hermitage, Guanaja 70% is Valrhona’s legendary dark chocolate blend. Developed in 1986, it was the first chocolate in the world to reach 70% cocoa while retaining a round, harmonious bitterness.',
                'sku' => 'CHOC-VAL-001',
                'price' => 12.50,
                'sale_price' => null,
                'cost_price' => 5.20,
                'stock_quantity' => 140,
                'stock_status' => 'in_stock',
                'is_featured' => true,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.10,
                'brand_slug' => 'valrhona',
                'categories' => ['dark-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Godiva Signature Gold Ballotin Pralines (24 Pieces)',
                'slug' => 'godiva-signature-gold-ballotin-24pcs',
                'short_description' => 'Belgian luxury praline assortment tied with Godiva’s signature gold satin ribbon.',
                'description' => 'A timeless selection of 24 signature Belgian chocolates, including hazelnut pralinés, dark ganache hearts, velvety caramels, and delicate white chocolate swirls.',
                'sku' => 'CHOC-GOD-002',
                'price' => 58.00,
                'sale_price' => 48.00,
                'cost_price' => 24.00,
                'stock_quantity' => 65,
                'stock_status' => 'in_stock',
                'is_featured' => true,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.35,
                'brand_slug' => 'godiva',
                'categories' => ['truffles-pralines', 'gift-boxes'],
                'image' => 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Lindt Excellence 85% Cocoa Extra Dark Bar',
                'slug' => 'lindt-excellence-85-dark-chocolate-bar',
                'short_description' => 'Smooth and intensely aromatic Swiss dark chocolate with balanced earthy complexity.',
                'description' => 'Crafted by Lindt’s Master Chocolatiers, this full-bodied bar offers an assertive cocoa intensity without sharpness. Roasted hazelnut undertones and deep cocoa richness define every bite.',
                'sku' => 'CHOC-LIN-003',
                'price' => 6.95,
                'sale_price' => null,
                'cost_price' => 2.90,
                'stock_quantity' => 250,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.10,
                'brand_slug' => 'lindt',
                'categories' => ['dark-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1548907040-4baa42d10919?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Neuhaus Brussels Marc de Champagne Dusted Truffles',
                'slug' => 'neuhaus-marc-de-champagne-dusted-truffles',
                'short_description' => 'Decadent dark chocolate ganache infused with authentic Marc de Champagne and dusted in fine cocoa.',
                'description' => 'From the historic inventors of the Belgian praline, these hand-finished truffles feature a velvety dark ganache delicately perfumed with fine Champagne distillate, rolled in bitter dark cocoa powder.',
                'sku' => 'CHOC-NEU-004',
                'price' => 36.00,
                'sale_price' => 29.50,
                'cost_price' => 14.50,
                'stock_quantity' => 45,
                'stock_status' => 'in_stock',
                'is_featured' => true,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.20,
                'brand_slug' => 'neuhaus',
                'categories' => ['truffles-pralines'],
                'image' => 'https://images.unsplash.com/photo-1575372587186-50020fd3b811?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Venchi Chocoviar 75% Dark Hazelnut Pearls (200g)',
                'slug' => 'venchi-chocoviar-75-dark-hazelnut-pearls',
                'short_description' => 'Exquisite Italian Gianduja cream encased in crisp dark chocolate and coated in Chocoviar caviar pearls.',
                'description' => 'Venchi’s world-famous Chocoviar: a soft core of Piedmont hazelnut Gianduja, wrapped in intense 75% dark chocolate and finished with glistening beads of 75% dark micro-pearls.',
                'sku' => 'CHOC-VEN-005',
                'price' => 34.00,
                'sale_price' => null,
                'cost_price' => 15.00,
                'stock_quantity' => 80,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.20,
                'brand_slug' => 'venchi',
                'categories' => ['truffles-pralines', 'barks-dragees'],
                'image' => 'https://images.unsplash.com/photo-1526081347589-7fa3cb41b4b2?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Lindt Swiss Classic Milk Chocolate with Whole Hazelnuts',
                'slug' => 'lindt-swiss-classic-milk-chocolate-hazelnut',
                'short_description' => 'Velvety Swiss milk chocolate loaded with slow-roasted whole hazelnuts.',
                'description' => 'Finest Alpine milk chocolate studded generously with premium roasted hazelnuts. The satisfying crunch meets the velvety smoothness of genuine Swiss conching.',
                'sku' => 'CHOC-LIN-006',
                'price' => 7.50,
                'sale_price' => null,
                'cost_price' => 3.10,
                'stock_quantity' => 190,
                'stock_status' => 'in_stock',
                'is_featured' => true,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.15,
                'brand_slug' => 'lindt',
                'categories' => ['milk-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Ghirardelli Sea Salt Caramel Filled Milk Chocolate Squares',
                'slug' => 'ghirardelli-sea-salt-caramel-milk-chocolate-squares',
                'short_description' => 'Rich milk chocolate squares with a luscious flowing sea salt caramel center.',
                'description' => 'San Francisco’s premier confectionery hallmark: slow-melting milk chocolate filled with luscious, buttery caramel touched with a pinch of California sea salt.',
                'sku' => 'CHOC-GHI-007',
                'price' => 14.99,
                'sale_price' => 11.99,
                'cost_price' => 6.00,
                'stock_quantity' => 110,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.25,
                'brand_slug' => 'ghirardelli',
                'categories' => ['milk-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1516738901171-8eb4fc13bd20?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Valrhona Ivoire 35% Bourbon Vanilla White Chocolate',
                'slug' => 'valrhona-ivoire-35-white-chocolate-bar',
                'short_description' => 'Subtle sweetness, pure cocoa butter, and warm Madagascan Bourbon vanilla.',
                'description' => 'Unlike overly sweet commercial white chocolates, Valrhona Ivoire features a gentle sugar profile, highlighting pure de-odorized cocoa butter and natural vanilla notes with warm milk undertones.',
                'sku' => 'CHOC-VAL-008',
                'price' => 13.50,
                'sale_price' => null,
                'cost_price' => 5.80,
                'stock_quantity' => 75,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.10,
                'brand_slug' => 'valrhona',
                'categories' => ['white-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Amedei Porcelana Single-Estate Extra Dark 70% Bar',
                'slug' => 'amedei-porcelana-single-estate-dark-bar',
                'short_description' => 'The world’s rarest translucent white cocoa beans transformed into Italian perfection.',
                'description' => 'Crafted exclusively from pure Criollo Porcelana beans harvested in small estates in Venezuela. Delicate notes of toasted almond, fresh brioche, and wild red berries with zero bitterness.',
                'sku' => 'CHOC-AME-009',
                'price' => 22.00,
                'sale_price' => null,
                'cost_price' => 10.50,
                'stock_quantity' => 40,
                'stock_status' => 'in_stock',
                'is_featured' => true,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.05,
                'brand_slug' => 'amedei-tuscany',
                'categories' => ['dark-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1587132137056-bfbf0166836e?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Patchi Prestige Velvet Royal Chocolate Hamper (48 Pieces)',
                'slug' => 'patchi-prestige-velvet-royal-hamper-48pcs',
                'short_description' => 'An opulent velvet presentation box filled with luxury Lebanese and Swiss confection art.',
                'description' => 'Individually dressed in gilded foil, each praline and ganache creation combines pure whole roasted hazelnuts, pistachios, crispy crêpe dentelle, and creamy gianduja cream.',
                'sku' => 'CHOC-PAT-010',
                'price' => 135.00,
                'sale_price' => 115.00,
                'cost_price' => 55.00,
                'stock_quantity' => 25,
                'stock_status' => 'in_stock',
                'is_featured' => true,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.85,
                'brand_slug' => 'patchi',
                'categories' => ['gift-boxes'],
                'image' => 'https://images.unsplash.com/photo-1549007953-2f2dc0b24019?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Ferrero Rocher Grand Hazelnut & Cocoa Praline Tower (32 Pieces)',
                'slug' => 'ferrero-rocher-grand-hazelnut-praline-tower-32pcs',
                'short_description' => 'The golden celebration tower featuring whole Piedmont hazelnuts and crispy wafer spheres.',
                'description' => 'A whole crunchy hazelnut at the heart, a delicious creamy hazelnut filling, a crisp wafer shell covered with milk chocolate and roasted hazelnut pieces.',
                'sku' => 'CHOC-FER-011',
                'price' => 26.50,
                'sale_price' => 21.00,
                'cost_price' => 11.00,
                'stock_quantity' => 180,
                'stock_status' => 'in_stock',
                'is_featured' => true,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.40,
                'brand_slug' => 'ferrero-rocher',
                'categories' => ['truffles-pralines', 'gift-boxes'],
                'image' => 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Leonidas Traditional Belgian Gianduja Hazelnut Ingot Bar',
                'slug' => 'leonidas-belgian-gianduja-hazelnut-ingot-bar',
                'short_description' => 'Velvety smooth paste of roasted Mediterranean hazelnuts and sweet milk chocolate.',
                'description' => 'Wrapped in gold foil, this classic Belgian Gianduja ingot melts effortlessly on the tongue, pairing the sweet scent of roasted hazelnuts with pure Belgian dairy butter.',
                'sku' => 'CHOC-LEO-012',
                'price' => 9.50,
                'sale_price' => null,
                'cost_price' => 4.00,
                'stock_quantity' => 130,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.15,
                'brand_slug' => 'leonidas',
                'categories' => ['milk-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1511381939415-e44015466834?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Ghirardelli Grand Velvety Double Chocolate Hot Cocoa Tin (454g)',
                'slug' => 'ghirardelli-double-chocolate-hot-cocoa-tin',
                'short_description' => 'Luxuriously deep and velvety drinking chocolate for steaming winter mugs.',
                'description' => 'Carefully balanced cocoa beans blended with pure sugar, vanilla, and real chocolate flakes to deliver an exceptionally smooth, rich, and decadent drinking experience.',
                'sku' => 'CHOC-GHI-013',
                'price' => 16.00,
                'sale_price' => 13.50,
                'cost_price' => 6.50,
                'stock_quantity' => 90,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.45,
                'brand_slug' => 'ghirardelli',
                'categories' => ['hot-chocolate-cocoa'],
                'image' => 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Valrhona 100% Dutch Processed Pure Cocoa Powder (250g)',
                'slug' => 'valrhona-pure-dutch-processed-cocoa-powder',
                'short_description' => 'Unsweetened premium pastry chef cocoa powder with a deep warm mahogany hue.',
                'description' => 'Sought after by three-star Michelin pastry chefs worldwide, this 100% pure cocoa powder boasts 21% cocoa butter for unmatched aromatics in hot beverages, truffles, and baking.',
                'sku' => 'CHOC-VAL-014',
                'price' => 18.50,
                'sale_price' => null,
                'cost_price' => 8.20,
                'stock_quantity' => 120,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.25,
                'brand_slug' => 'valrhona',
                'categories' => ['hot-chocolate-cocoa'],
                'image' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Neuhaus Dark Chocolate Roasted Valencia Almond Bark (180g)',
                'slug' => 'neuhaus-dark-chocolate-valencia-almond-bark',
                'short_description' => 'Hand-broken slabs of 64% Costa Rica dark chocolate with caramelized Valencia almonds.',
                'description' => 'Generous shards of artisanal dark chocolate studded with slow-caramelized Spanish almonds and a kiss of Guérande sea salt.',
                'sku' => 'CHOC-NEU-015',
                'price' => 19.50,
                'sale_price' => null,
                'cost_price' => 8.80,
                'stock_quantity' => 95,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.18,
                'brand_slug' => 'neuhaus',
                'categories' => ['barks-dragees', 'dark-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1570476922354-81227cdbb76c?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Venchi Dark Chocolate Covered Arabica Espresso Coffee Beans',
                'slug' => 'venchi-dark-chocolate-covered-arabica-espresso-beans',
                'short_description' => 'Crisp roasted Santos Arabica beans smothered in 70% dark Italian chocolate.',
                'description' => 'A punchy collision of Italian espresso culture and master chocolaterie: whole single-origin coffee beans roasted to perfection and enrobed in layers of bitter-sweet chocolate.',
                'sku' => 'CHOC-VEN-016',
                'price' => 15.00,
                'sale_price' => 12.00,
                'cost_price' => 6.20,
                'stock_quantity' => 140,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.15,
                'brand_slug' => 'venchi',
                'categories' => ['barks-dragees'],
                'image' => 'https://images.unsplash.com/photo-1526081347589-7fa3cb41b4b2?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Lindt Zero Sugar Added 70% Cocoa Dark Chocolate Bar',
                'slug' => 'lindt-zero-sugar-70-dark-chocolate-bar',
                'short_description' => 'Stevia-sweetened keto friendly Swiss dark chocolate without compromise on rich taste.',
                'description' => 'All the hallmark creaminess and aroma of Lindt Excellence, sweetened naturally with plant-based stevia. Perfect for keto and mindful chocolate lovers.',
                'sku' => 'CHOC-LIN-017',
                'price' => 8.50,
                'sale_price' => null,
                'cost_price' => 3.90,
                'stock_quantity' => 85,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.10,
                'brand_slug' => 'lindt',
                'categories' => ['sugar-free-vegan', 'dark-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1548907040-4baa42d10919?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Amedei Vegan Oat Milk 55% Creamy Cocoa Bar',
                'slug' => 'amedei-vegan-oat-milk-55-creamy-cocoa-bar',
                'short_description' => 'Award winning dairy-free artisan milk chocolate crafted with gluten-free oat milk.',
                'description' => 'A masterstroke in vegan confectionery by Amedei Tuscany. Premium Venezuelan cocoa combined with micro-milled toasted oats produces a melt that rivals traditional dairy chocolate.',
                'sku' => 'CHOC-AME-018',
                'price' => 16.00,
                'sale_price' => null,
                'cost_price' => 7.00,
                'stock_quantity' => 60,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.07,
                'brand_slug' => 'amedei-tuscany',
                'categories' => ['sugar-free-vegan', 'milk-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1587132137056-bfbf0166836e?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Godiva Strawberry & Cream White Chocolate Tablet',
                'slug' => 'godiva-strawberry-cream-white-chocolate-tablet',
                'short_description' => 'Silky white chocolate bar infused with tart freeze-dried strawberry crumbles.',
                'description' => 'Rich Belgian white chocolate infused with the sunny tang of handpicked summer strawberries and vanilla bean butter.',
                'sku' => 'CHOC-GOD-019',
                'price' => 9.00,
                'sale_price' => null,
                'cost_price' => 3.80,
                'stock_quantity' => 115,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.10,
                'brand_slug' => 'godiva',
                'categories' => ['white-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Leonidas Heritage Master Dark Ganache Collection (16 Pieces)',
                'slug' => 'leonidas-heritage-master-dark-ganache-16pcs',
                'short_description' => 'Fresh Belgian dark chocolate pralines filled with single-origin cocoa ganache infusions.',
                'description' => 'Handcrafted fresh daily with pure cocoa butter. Features inclusions of Earl Grey tea, red currant reduction, and salted butter caramel enveloped in 72% dark shells.',
                'sku' => 'CHOC-LEO-020',
                'price' => 38.00,
                'sale_price' => 31.00,
                'cost_price' => 16.00,
                'stock_quantity' => 50,
                'stock_status' => 'in_stock',
                'is_featured' => true,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.25,
                'brand_slug' => 'leonidas',
                'categories' => ['truffles-pralines', 'gift-boxes'],
                'image' => 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Venchi Cremino 1878 Triple Layer Gianduja Bar',
                'slug' => 'venchi-cremino-1878-triple-layer-gianduja-bar',
                'short_description' => 'A heritage recipe of alternating layers of almond paste and hazelnut Gianduja.',
                'description' => 'The timeless Piedmontese masterpiece: two layers of luscious hazelnut Gianduja sandwiching a delicate middle layer of white almond cream.',
                'sku' => 'CHOC-VEN-021',
                'price' => 11.50,
                'sale_price' => null,
                'cost_price' => 4.90,
                'stock_quantity' => 105,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.11,
                'brand_slug' => 'venchi',
                'categories' => ['milk-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Patchi Artisan Dark Chocolate Candied Orange Peel Strips (150g)',
                'slug' => 'patchi-dark-chocolate-candied-orange-peel',
                'short_description' => 'Sun-drenched Mediterranean orange rind glaced in syrup and dipped in 70% dark chocolate.',
                'description' => 'The quintessential luxury citrus pairing. Succulent candied orange rinds with a firm tender bite, half-dipped in bittersweet Lebanese dark chocolate.',
                'sku' => 'CHOC-PAT-022',
                'price' => 24.00,
                'sale_price' => 19.50,
                'cost_price' => 9.50,
                'stock_quantity' => 70,
                'stock_status' => 'in_stock',
                'is_featured' => false,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.15,
                'brand_slug' => 'patchi',
                'categories' => ['barks-dragees', 'dark-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1570476922354-81227cdbb76c?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Valrhona Dulcey 35% Blond Toasted Caramel Chocolate Bar',
                'slug' => 'valrhona-dulcey-35-blond-caramel-chocolate-bar',
                'short_description' => 'The world’s first blond chocolate with buttery biscuit notes and a pinch of salt.',
                'description' => 'Created through slow caramelization of milk sugars during gentle conching. Dulcey presents a creamy, biscuity mouthfeel with a delicate roasted caramel character.',
                'sku' => 'CHOC-VAL-023',
                'price' => 14.00,
                'sale_price' => null,
                'cost_price' => 6.20,
                'stock_quantity' => 90,
                'stock_status' => 'in_stock',
                'is_featured' => true,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.10,
                'brand_slug' => 'valrhona',
                'categories' => ['white-chocolate'],
                'image' => 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?q=80&w=800&auto=format&fit=crop',
            ],
            [
                'name' => 'Godiva Connoisseur Midnight Dark Truffles Gift Box (12 Pieces)',
                'slug' => 'godiva-connoisseur-midnight-dark-truffles-12pcs',
                'short_description' => 'Six distinct expressions of extra dark cocoa ganache in an embossed velvet box.',
                'description' => 'An ode to the dark chocolate purist. Features 72% Santo Domingo cacao truffles, black raspberry infusions, smoked sea salt dark hearts, and Aztec chili cocoa pearls.',
                'sku' => 'CHOC-GOD-024',
                'price' => 42.00,
                'sale_price' => 34.00,
                'cost_price' => 18.00,
                'stock_quantity' => 60,
                'stock_status' => 'in_stock',
                'is_featured' => true,
                'status' => 'published',
                'is_active' => true,
                'weight' => 0.20,
                'brand_slug' => 'godiva',
                'categories' => ['truffles-pralines', 'gift-boxes'],
                'image' => 'https://images.unsplash.com/photo-1575372587186-50020fd3b811?q=80&w=800&auto=format&fit=crop',
            ],
        ];

        foreach ($productsData as $p) {
            $brand = $brands[$p['brand_slug']] ?? null;

            $product = Product::updateOrCreate(
                ['sku' => $p['sku']],
                [
                    'name' => $p['name'],
                    'slug' => $p['slug'],
                    'short_description' => $p['short_description'],
                    'description' => $p['description'],
                    'price' => $p['price'],
                    'sale_price' => $p['sale_price'],
                    'cost_price' => $p['cost_price'],
                    'stock_quantity' => $p['stock_quantity'],
                    'stock_status' => $p['stock_status'],
                    'is_featured' => $p['is_featured'],
                    'status' => $p['status'],
                    'is_active' => $p['is_active'],
                    'weight' => $p['weight'],
                    'brand_id' => $brand?->id,
                ]
            );

            // Sync categories
            $catIds = [];
            foreach ($p['categories'] as $catSlug) {
                if (isset($categories[$catSlug])) {
                    $catIds[] = $categories[$catSlug]->id;
                }
            }
            $product->categories()->sync($catIds);

            // Attach primary image
            ProductImage::updateOrCreate(
                ['product_id' => $product->id, 'is_primary' => true],
                [
                    'path' => $p['image'],
                    'alt' => $p['name'],
                    'sort_order' => 1,
                ]
            );
        }

        // Active Flash Sale setup
        $flashSale = FlashSale::updateOrCreate(
            ['title' => 'Weekend Gourmet Chocolate Flash Sale'],
            [
                'starts_at' => now()->subDay(),
                'ends_at' => now()->addDays(3),
                'is_active' => true,
            ]
        );

        $flashProducts = Product::whereNotNull('sale_price')->limit(4)->get();
        foreach ($flashProducts as $fp) {
            FlashSaleProduct::updateOrCreate(
                ['flash_sale_id' => $flashSale->id, 'product_id' => $fp->id],
                [
                    'discount_price' => $fp->sale_price,
                    'allocated_quantity' => 20,
                    'sold_quantity' => 8,
                ]
            );
        }
    }
}
