name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v7

      # 2. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, pdo, pdo_mysql
          tools: composer
          coverage: none

      # 3. Composer is needed ONLY on GitHub
      # Required by Laravel/Wayfinder during the frontend build
      - name: Install Composer dependencies
        run: |
          composer install \
            --no-interaction \
            --prefer-dist \
            --no-dev \
            --optimize-autoloader \
            --no-progress

      # 4. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 20
          cache: npm

      # 5. Install frontend dependencies
      - name: Install npm dependencies
        run: npm ci --prefer-offline --no-audit --no-fund

      # 6. Build frontend EVERY push
      - name: Build frontend
        run: npm run build

      # 7. Upload only changed files
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21

          # /home/doxqkwec/choco/
          server-dir: /

          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/.env
            **/storage/logs/**
            **/tests/**
            **/.github/**